# Site settings
title: Michael.Y's Blog
email: yangxing20107@gmail.com
description: you konw they said that silent water runs deep.
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: yxzoro
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/yxzoro/blog/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/yxzoro/new/master
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: yxzoro
disqus_url: "http://yxzoro.github.io"
#########################################

# Build settings
# markdown: kramdown
markdown: markdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
